### ISSUE TITLE
Disable auto mounting 

### ISSUE THREAD

**Issue by veenabalakrishna** [anthcourtney/ansible-role-cis-amazon-linux#12]
Thanks for the ansible role.

I am on Amazon linux 2017.03 with ansible 2.3 and facing issue with autofs

TASK [ansible-role-cis-amazon-linux : 1.1.19 - Disable autofs] **************************************************************************
task path: /home/ec2-user/os-hardening-amazon-linux/ansible-role-cis-amazon-linux/tasks/level-1/1.1.19.yml:6
fatal: [1]: FAILED! => {"changed": false, "failed": true, "failed_when_result": true, "msg": "Could not find the requested service autofs: host"}

**Comment by chandanchowdhury** [comment]
Hi @veenabalakrishna, are you still facing the issue?

**Comment by chandanchowdhury** [comment]
Closing as no reply
