### ISSUE TITLE
ansible-lint findings cleanup?

### ISSUE THREAD

**Issue by mcodd** [anthcourtney/ansible-role-cis-amazon-linux#13]
Hi!  We just started using this role and incorporated it into our internal ansible roles repo - we also use https://github.com/willthames/ansible-lint and have that automated to run against all our roles.  We noticed that it reports a lot of lint for ansible-role-cis-amazon-linux.  Would you be ok with me submitting a PR to clean up what that finds as lint (mostly trailing whitespace and some deprecated roles) or would you rather not?  No worries either way, but if you'd accept a PR we'll move that direction instead of having our internal system exclude this role (since we want to keep it updating going forward and don't want huge diffs between our internal copy and this one)!

thanks!
matt

**Comment by anthcourtney** [comment]
Hello Matt,

PRs are always welcome. Sling one this way and we'll make it happen.

thanks,
Anth
