### ISSUE TITLE
3.4.2: cis_hosts_allow_all_ips should accept list instead of string

### ISSUE THREAD

**Issue by Pratima** [anthcourtney/ansible-role-cis-amazon-linux#18]
There can be multiple IP ranges/subnets that would need access to the instance of this AMI in a secured environment. Would be good to have this var as a list rather than a single input.

**Comment by anthcourtney** [comment]
Thanks for the issue and the proposed PR.

I can somewhat see the value in this, but at the same time, `hosts.allow` and `hosts.deny` already allow for multiple ip ranges/subnets to be specified in the one entry as a comma-delimited list.

Changing the role from expecting a string to expecting a list would break any existing definitions that people using the role have.

**Comment by chandanchowdhury** [comment]
Hi @Pratima,
are you okay to close this issue?

**Comment by chandanchowdhury** [comment]
Closing assuming no answer as yes
