### ISSUE TITLE
 BSD or MIT license?

### ISSUE THREAD

**Issue by highc007** [anthcourtney/ansible-role-cis-amazon-linux#64]
While reviewing this item, we noticed an inconsistency between the license referenced in the 'external' descriptor at:
https://github.com/anthcourtney/ansible-role-cis-amazon-linux/blob/master/meta/main.yml
License
BSD.

And what is indicated in the actual code one would download, ~/meta/main.yml indicates:
license: MIT

While both are license types I'm generally permitted to work with, I'll need to know which prevails.
Also, I'll note that both BSD and MIT require
"The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."
and I'm not finding the notice anywhere in the material I'd download; if I've missed it somewhere, please advise.
Thanks,
Chris.

**Comment by chandanchowdhury** [comment]
Hey @highc007, thanks for finding the inconsistency.

It looks like the meta/main.yml was updated to MIT on 8afc2c25b4826a87136601618d50e6a234147962, and later README was updated with BSD on 8feccf057daa0f247afc6281ece5d7655f650490.

Also, looks like the meta/main.yml was copied and updated, probably leaving the License field as is, so I would assume @anthcourtney wanted to go with BSD.

However, I do not have deeper knowledge of the licenses or know if my assumption is correct, so I would leave it to @anthcourtney to decide.

**Comment by HarryHarcourt** [comment]
Whilst I will wait for @anthcourtney to answer, I feel the MIT license is clearer / cleaner and simpler than the BSD one (as there are variants).
So as a consumer of @anthcourtney Ansible Role and modified it to fit RHEL (because the framework is great) I would be happier with the MIT one.  [https://github.com/HarryHarcourt/Ansible-RHEL7-CIS-Benchmarks](Let me know because I need to adjust this accordingly).

**Comment by highc007** [comment]
While pondering some other Galaxy/github items, I notice project
https://github.com/oravirt/ansible-oracle-modules
has a LICENSE item at the 'very top'.  I gather this is a 'best practice', once this issue is settled out; would it be possible to 'so document' for this project?

**Comment by chandanchowdhury** [comment]
@highc007 
Absolutely, once @anthcourtney makes a decision, will add the corresponding LICENSE file.
